config/routes.rb
Rails.application.routes.draw do
  resources :customers

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :orders
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer

  has_many :order_pizzas
  has_many :pizzas, through: :order_pizzas
end

app/models/order_pizza.rb
class OrderPizza < ApplicationRecord
  belongs_to :order
  belongs_to :pizza
end

app/models/pizza.rb
class Pizza < ApplicationRecord

  has_many :order_pizzas
  has_many :orders, through: :order_pizzas
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end

  def show
  end

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.new(customer_params)

    if @customer.save
      redirect_to customers_path
    else
      render :new
    end
  end

  def edit
  end

private

  def customer_params
    params.require(:customer).permit(:name, :address)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/edit.html.erb
<h1>Customers#edit</h1>
<p>Find me in app/views/customers/edit.html.erb</p>

app/views/customers/index.html.erb
<h1>Customers</h1>

<%= link_to "Add New Customer", new_customer_path %>

<ul>
  <% @customers.each do |customer| %>
    <li>
      Name: <%= customer.name %>
    </li>
  <% end %>
</ul>

app/views/customers/new.html.erb
<h1>Add a new Customers</h1>

<%= form_for @customer do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>

  <%= form.label :address %>
  <%= form.text_field :address %>
  <%= form.submit %>
<% end %>

app/views/customers/show.html.erb
<h1>Customers#show</h1>
<p>Find me in app/views/customers/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PizzaShopTurbo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>